# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abadpassword
      POSTGRES_USER: pygridUser
      POSTGRES_DB: testDB
    ports:
      - 5432:5432
    networks:
      - pygrid-net

  pygrid:
    # image: mkenney1/artificien_pygrid:latest
    build: ../
    restart: always
    environment:
      NODE_ID: testnode4
      ADDRESS: http://localhost:5000
      PORT: 5000
      MASTER_NODE_URL: 172.18.177.169:5001
      DATABASE_URL: postgresql://pygridUser:abadpassword@db:5432/
    links:
        - db
    ports:
      - 5000:5000
    networks:
      - pygrid-net

  masternode:
    # image: mkenney1/artificien_orchestration:latest
    build: ~/Repos/artificien_orchestration_node
    restart: always
    environment:
      LOCALTEST: 'True'
    ports:
      - 5001:5001
    networks:
      - pygrid-net
    volumes:
      - ~/.aws/:/root/.aws  # Share AWS Creds with container

  jupyter:
    build : ./jupyter
    restart: always
    environment:
      JUPYTERHUB_USER: kenneym
    ports:
      - 8888:8888
    networks:
      - pygrid-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - pygrid-net

networks:
  pygrid-net:
