# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abadpassword
      POSTGRES_USER: pygridUser
      POSTGRES_DB: testDB
    ports:
      - 5432:5432
    networks:
      - pygrid-net

  pygrid:
    image: mkenney1/artificien_pygrid
    build: ../
    restart: always
    environment:
      NODE_ID: testnode4
      ADDRESS: http://localhost:5000
      PORT: 5000
      MASTER_NODE_URL: http://localhost:5001
      DATABASE_URL: postgresql://pygridUser:abadpassword@db:5432/
    links:
        - db
    ports:
      - 5000:5000
    networks:
      - pygrid-net


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - pygrid-net

networks:
  pygrid-net:
